/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConcursosRouteImport } from './routes/concursos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as EstagioRouteImport } from './routes/estagio'
import { Route as VagasRouteImport } from './routes/vagas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursosRoute = ConcursosRouteImport.update({
  id: '/concursos',
  path: '/concursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstagioRoute = EstagioRouteImport.update({
  id: '/estagio',
  path: '/estagio',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concursos': typeof ConcursosRoute
  '/cursos': typeof CursosRoute
  '/estagio': typeof EstagioRoute
  '/vagas': typeof VagasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concursos': typeof ConcursosRoute
  '/cursos': typeof CursosRoute
  '/estagio': typeof EstagioRoute
  '/vagas': typeof VagasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concursos': typeof ConcursosRoute
  '/cursos': typeof CursosRoute
  '/estagio': typeof EstagioRoute
  '/vagas': typeof VagasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/concursos' | '/cursos' | '/estagio' | '/vagas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/concursos' | '/cursos' | '/estagio' | '/vagas'
  id: '__root__' | '/' | '/concursos' | '/cursos' | '/estagio' | '/vagas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcursosRoute: typeof ConcursosRoute
  CursosRoute: typeof CursosRoute
  EstagioRoute: typeof EstagioRoute
  VagasRoute: typeof VagasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concursos': {
      id: '/concursos'
      path: '/concursos'
      fullPath: '/concursos'
      preLoaderRoute: typeof ConcursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estagio': {
      id: '/estagio'
      path: '/estagio'
      fullPath: '/estagio'
      preLoaderRoute: typeof EstagioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcursosRoute: ConcursosRoute,
  CursosRoute: CursosRoute,
  EstagioRoute: EstagioRoute,
  VagasRoute: VagasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
