/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConcursosRouteImport } from './routes/concursos'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as CurriculoRouteImport } from './routes/curriculo'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstagioRouteImport } from './routes/estagio'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedMeusCursosRouteImport } from './routes/_authenticated/meus-cursos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as CertificadoCodigoRouteImport } from './routes/certificado.$codigo'
import { Route as CursoSlugRouteImport } from './routes/curso.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin/cursos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursosRoute = ConcursosRouteImport.update({
  id: '/concursos',
  path: '/concursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoRoute = CurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstagioRoute = EstagioRouteImport.update({
  id: '/estagio',
  path: '/estagio',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusCursosRoute = AuthenticatedMeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CertificadoCodigoRoute = CertificadoCodigoRouteImport.update({
  id: '/certificado/$codigo',
  path: '/certificado/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugRoute = CursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/concursos': typeof ConcursosRoute
  '/conteudos': typeof ConteudosRoute
  '/curriculo': typeof CurriculoRoute
  '/cursos': typeof CursosRoute
  '/entrar': typeof EntrarRoute
  '/estagio': typeof EstagioRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/concursos': typeof ConcursosRoute
  '/conteudos': typeof ConteudosRoute
  '/curriculo': typeof CurriculoRoute
  '/cursos': typeof CursosRoute
  '/entrar': typeof EntrarRoute
  '/estagio': typeof EstagioRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/vagas': typeof VagasRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/concursos': typeof ConcursosRoute
  '/conteudos': typeof ConteudosRoute
  '/curriculo': typeof CurriculoRoute
  '/cursos': typeof CursosRoute
  '/entrar': typeof EntrarRoute
  '/estagio': typeof EstagioRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/certificado/$codigo': typeof CertificadoCodigoRoute
  '/curso/$slug': typeof CursoSlugRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/concursos'
    | '/conteudos'
    | '/curriculo'
    | '/cursos'
    | '/entrar'
    | '/estagio'
    | '/redefinir-senha'
    | '/sobre'
    | '/vagas'
    | '/admin'
    | '/certificados'
    | '/meus-cursos'
    | '/painel'
    | '/certificado/$codigo'
    | '/curso/$slug'
    | '/admin/cursos'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/concursos'
    | '/conteudos'
    | '/curriculo'
    | '/cursos'
    | '/entrar'
    | '/estagio'
    | '/redefinir-senha'
    | '/sobre'
    | '/vagas'
    | '/certificados'
    | '/meus-cursos'
    | '/painel'
    | '/certificado/$codigo'
    | '/curso/$slug'
    | '/admin/cursos'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/concursos'
    | '/conteudos'
    | '/curriculo'
    | '/cursos'
    | '/entrar'
    | '/estagio'
    | '/redefinir-senha'
    | '/sobre'
    | '/vagas'
    | '/_authenticated/admin'
    | '/_authenticated/certificados'
    | '/_authenticated/meus-cursos'
    | '/_authenticated/painel'
    | '/certificado/$codigo'
    | '/curso/$slug'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConcursosRoute: typeof ConcursosRoute
  ConteudosRoute: typeof ConteudosRoute
  CurriculoRoute: typeof CurriculoRoute
  CursosRoute: typeof CursosRoute
  EntrarRoute: typeof EntrarRoute
  EstagioRoute: typeof EstagioRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreRoute: typeof SobreRoute
  VagasRoute: typeof VagasRoute
  CertificadoCodigoRoute: typeof CertificadoCodigoRoute
  CursoSlugRoute: typeof CursoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concursos': {
      id: '/concursos'
      path: '/concursos'
      fullPath: '/concursos'
      preLoaderRoute: typeof ConcursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo': {
      id: '/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof CurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estagio': {
      id: '/estagio'
      path: '/estagio'
      fullPath: '/estagio'
      preLoaderRoute: typeof EstagioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-cursos': {
      id: '/_authenticated/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof AuthenticatedMeusCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificado/$codigo': {
      id: '/certificado/$codigo'
      path: '/certificado/$codigo'
      fullPath: '/certificado/$codigo'
      preLoaderRoute: typeof CertificadoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug': {
      id: '/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof CursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedMeusCursosRoute: typeof AuthenticatedMeusCursosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedMeusCursosRoute: AuthenticatedMeusCursosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConcursosRoute: ConcursosRoute,
  ConteudosRoute: ConteudosRoute,
  CurriculoRoute: CurriculoRoute,
  CursosRoute: CursosRoute,
  EntrarRoute: EntrarRoute,
  EstagioRoute: EstagioRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreRoute: SobreRoute,
  VagasRoute: VagasRoute,
  CertificadoCodigoRoute: CertificadoCodigoRoute,
  CursoSlugRoute: CursoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
